### ISSUE TITLE
compilation error when using SchemaType

### ISSUE THREAD

**Issue by london-coder** [eclipsesource/play-json-schema-validator#139]
HI,

I'm trying to learn you library using the examples in the README.md on the github page. When using:

```val schema: SchemaType = Json.fromJson[SchemaType](
	"""
      |{
	  |  "$schema": "http://json-schema.org/draft-04/schema#",
	  |  "title": "Group Structure Response", .... too long to include
```

And importing ...
import com.eclipsesource.schema._
import play.api.libs.json._

when using sbt compile, I get the  error:
 "No Json deserializer found for type com.eclipsesource.schema.SchemaType. Try to implement an implicit Reads or Format for this type."

Clearly I am doing something wrong, but it is not clear from the example code what is necessary / missing.

Any advise to help me resolve this will be appreciated.

Regards
Alan

**Comment by edgarmueller** [comment]
Hi, the `Reads` and `Writes` for `SchemaType` are draft specific, hence you need to import the respective Version object, in this case `Version4` (e.g. as in https://github.com/eclipsesource/play-json-schema-validator/blob/master/src/test/scala/com/eclipsesource/schema/AdditionalItemsSpec.scala#L10-L14, also see [usage notes](https://github.com/eclipsesource/play-json-schema-validator#usage)). Let me know if that helps, if it doesn't, please post your entire code, so that I can reproduce the error.

**Comment by london-coder** [comment]
Many thanks Edgar. Your help enabled me to compile the code successfully. I am happy to have this issue closed.

**Comment by edgarmueller** [comment]
Ok, great! If there's anythings else, let me know.
