### ISSUE TITLE
How do i use pattern? 

### ISSUE THREAD

**Issue by sheshankkodam** [eclipsesource/play-json-schema-validator#23]
First of all thanks for providing the validator ... very helpful especially beginners in scala like me .. 

Question: How do i use patterns? I have the input and schema as shown below which doesnt work. 

```scala
{
	"id": "398402",
	"start": "2016-01-04T18:31:00Z"
}

 val schema = Json.fromJson[SchemaType](Json.parse(
    """{
      |"properties": {
      |  "id":    { "type": "string" },
      |  "spoolStart":  { "type": "string",
      |                         "pattern": "^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z"
      |                       }
      |}
    }""".stripMargin)).get

**Comment by edgarmueller** [comment]
Hi,
the problem is that `\d` in this context is an invalid escape character, so the JSON parser will complain about it.
If you have a look at [spec](http://json-schema.org/latest/json-schema-validation.html#anchor6), the preferred way to specify a character class is via brackets, so for your example this should work:

```Scala
 val schema = Json.fromJson[SchemaType](Json.parse(
        """{
          |  "properties": {
          |    "id":    { "type": "string" },
          |    "spoolStart":  {
          |      "type": "string",
          |      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z"
          |    }
          |  }
          |}""".stripMargin)).get
```
Alternatively you could also double escape the character class like in `\\d`, which is also ought to work. Besides that, I noticed that you pass a JSON instance with a property named `start`, which perhaps should be named `spoolStart`.

**Comment by sheshankkodam** [comment]
Hello, 

I tried this pattern too "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z but felt its too long and not very easy to read. 

So wanted to ask you if there is any other way. 

Yes you're right ... the JSON field name should be spoolStart

**Comment by sheshankkodam** [comment]
If i have any questions like this, is there a document/file which i can use for reference?

**Comment by edgarmueller** [comment]
I found [this guide](http://spacetelescope.github.io/understanding-json-schema/index.html) to be a very good intro to JSON Schema.
Regarding readabilty: I think for your use-case you could stick to the `format` keyword with the format being set to `date-time`, but the validator currently does not yet support `format`s. I've created issue #24 to track it.
