### ISSUE TITLE
int32 | int64 validator for integer property type

### ISSUE THREAD

**Issue by avkonst** [eclipsesource/play-json-schema-validator#93]
Hi,

I have tested int32 | int64 format validator. It seems it works for number property type. I thought that Swagger spec allows format spec only for integer property type, which is missing.

Here is what I do:
- I persist object in a database. JSON schema describes an instance.
- I inspect the schema and identify object properties and it's types.
- For number type I use double. It works fine and handles overflows, as double just drops precision when there is no enough bits to save all
- For integer type I use BigDecimal if no format is specified, use Long if format is int64, and use Int if format is int32.

So, I effectively did not have an issue with number property type, I had an overflow of an integer. If you could let me know how I could fix it myself, I could contribute.

**Comment by edgarmueller** [comment]
Got it, I forgot to actually validate the format for `integer`s, although everything else is in place. I don't think this should be much of a hassle to fix. You'd need to pull up the `validateFormat` method to the `NumberConstraintsValidator` and call that within the `IntegerValidator`. Please note that in case you want to contribute, you should do so against the `scala-2.11` branch, since master is on 2.12 and has some breaking changes against 2.11 (the 0.8.7 release was also created from the `scala-2.11` branch).

Let me know if you want to take care of that (contributions are very welcome!). Otherwise I'll add additional tests and update in the evening.

**Comment by avkonst** [comment]
I will have a look tomorrow if I can follow you instructions.

**Comment by edgarmueller** [comment]
I've pushed a PR. Maybe you could take a look to be sure it fits your needs? If so, I will backport the fix to the scala-2.11 branch.

**Comment by avkonst** [comment]
Thanks. I have reviewed it with some comments. I certainly could not fix it
that quick and that elegant. I do not know how to verify it in my product
without having a package released. If you could educate me how it can be
done, I will do.

Regards,
Andrey

**Comment by edgarmueller** [comment]
Thanks for your review. This should be fixed with 0.8.8.
